FROM node:16

ENV APP_ROOT /app

RUN mkdir ${APP_ROOT}
WORKDIR ${APP_ROOT}
ADD . ${APP_ROOT}

# RUN apt update && apt dist-upgrade -y && \
#   apt install software-properties-common -y && \
#   add-apt-repository ppa:ethereum/ethereum && \
#   apt update -y && \
#   apt install solc -y

RUN yarn install
RUN yarn global add \
  solhint \
  solc \
  eslint \
  typescript

EXPOSE 8545

CMD [ "yarn", "dev" ]
